<a href="https://colab.research.google.com/github/ultra151/cv/blob/main/ComputerVision%EB%AA%A8%EB%8D%B8%EC%84%A4%EA%B3%84/Day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

스칼라

In [ ]:
10

10

1차원 텐서(배열/백터)

In [ ]:
a=np.array([1,2,3,4])

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
a.shape

(4,)

In [ ]:
import tensorflow as tf
tf.constant([1,2,3,4])
t=tf.Variable([1,2,3,4])

In [ ]:
t

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
(1,2,3,4)

(1, 2, 3, 4)

In [ ]:
[1,2,3,4]

[1, 2, 3, 4]

In [ ]:
t.assign_add([1,1,1,1]).numpy()

array([3, 4, 5, 6], dtype=int32)

In [ ]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [ ]:
t=np.array([[1,2,3,4],[1,2,3,4]])

In [ ]:
t.sum(axis=0)

array([2, 4, 6, 8])

In [ ]:
t.sum(axis=1)

array([10, 10])

In [ ]:
len(t[0])

4

In [ ]:
t.shape

(2, 4)

In [ ]:
t.size

8

In [ ]:
t.ndim

2

In [ ]:
np.array([1,'aswe']).shape

(2,)

In [ ]:
tf.Variable(1).shape

TensorShape([])

In [ ]:
k=[(1,2,3,4,5)]

In [ ]:
tf.Variable(k).shape

TensorShape([1, 5])

In [ ]:
t

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [ ]:
c_t=t.reshape((2,4,1))

In [ ]:
c_t.shape

(2, 4, 1)

In [ ]:
t.reshape((3,4,1))

ValueError: cannot reshape array of size 8 into shape (3,4,1)

데이터 구조 관점 차원
- .shape 을 이용하여 나타난 수 갯수

데이터 피처 관점 차원
- 피처수가 차원의 수를 의미

In [ ]:
from keras.datasets import mnist,cifar10
(tr_x,tr_y),(tt_x,tt_y)=mnist.load_data()

In [ ]:
tr_x.shape

(60000, 28, 28)

In [ ]:
tt_x.shape

(10000, 28, 28)

In [ ]:
s_tr_x=tr_x.reshape((60000,28,28,1))

In [ ]:
s_tr_x.shape

(60000, 28, 28, 1)

In [ ]:
(tr_x,tr_y),(tt_x,tt_y)=cifar10.load_data()
tr_x.shape

170498071/170498071 ━━━━━━━━━━━━━━━━━━━━ 3s 0us/step


(50000, 32, 32, 3)